language: python
python:
  - "3.6.3"
install:
  - pip install -r requirements.pip
script:
  - coverage run --source=src/models -m unittest tests/models/*.py && coverage report
after_success:
  - coveralls