version: '3.6'
services:
  intive-fdv_app:
    container_name: intive-fdv_app
    build: .
    stdin_open: ${DOCKERTTY}
    tty: ${DOCKERTTY}
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    command: python src/main.py
    env_file:
      - '.env'
